export const PIZZA_LIST_REQUEST = 'PIZZA_LIST_REQUEST'
export const PIZZA_LIST_SUCCESS = 'PIZZA_LIST_SUCCESS'
export const PIZZA_LIST_FAIL = 'PIZZA_LIST_FAIL'

export const ADD_PIZZA_REQUEST = 'ADD_PIZZA_REQUEST'
export const ADD_PIZZA_SUCCESS = 'ADD_PIZZA_SUCCESS'
export const ADD_PIZZA_FAIL = 'ADD_PIZZA_FAIL'
export const RESET_FORM = 'RESET_FORM'

export const GET_PIZZA_BY_ID_REQUEST = 'GET_PIZZA_BY_ID_REQUEST'
export const GET_PIZZA_BY_ID_SUCCESS = 'GET_PIZZA_BY_ID_SUCCESS'
export const GET_PIZZA_BY_ID_FAIL = 'GET_PIZZA_BY_ID_FAIL'

export const EDIT_PIZZA_REQUEST = 'EDIT_PIZZA_REQUEST '
export const EDIT_PIZZA_SUCCESS = 'EDIT_PIZZA_SUCCESS'
export const EDIT_PIZZA_FAIL = 'EDIT_PIZZA_FAIL'
